--- 
- name: tomcat9 installation on ubuntu
  become: yes
  hosts: all
  tasks:
    - name: update cache
      apt:
        update_cache: yes
        state: present
    - name: installation of java 11
      apt:
        name: openjdk-11-jdk
        state: present
    - name: user tomcat
      user:
        create_home: yes
        home: /opt/tomcat
        name: tomcat
        shell: /bin/false
        state: present
    - name: group tomcat
      group:
        name: tomcat
        state: present
        

