--- 
- name: tomcat9 installation on ubuntu
  become: yes
  hosts: all
  vars:
    - java_version: 'openjdk-11-jdk'
    - tomcat_user: tomcat
    - home_dir: /opt/tomcat
    - default_shell: /bin/false
  tasks:
    - name: update cache
      apt:
        update_cache: yes
        state: present
    - name: installation of java 11
      apt:
        name: "{{ java_version }}"
        state: present
    - name: user tomcat
      user: 
        create_home: yes
        home: "{{ home_dir }}"
        name: "{{ tomcat_user }}"
        shell: "{{ default_shell }}"
        state: present
    - name: group tomcat
      group:
        name: "{{ tomcat_user }}"
        state: present


