--- 
- name: tomcat9 installation on ubuntu
  become: yes
  hosts: all
  vars:
    - java_version: 'openjdk-11-jdk'
    - tomcat_user: tomcat
    - home_dir: /opt/tomcat
    - default_shell: /bin/false
    - version: 9.0.65
  tasks:
    - name: update cache
      apt:
        update_cache: yes
        state: present
    - name: installation of java 11
      apt:
        name: "{{ java_version }}"
        state: present
    - name: user tomcat
      user: 
        create_home: yes
        home: "{{ home_dir }}"
        name: "{{ tomcat_user }}"
        shell: "{{ default_shell }}"
        state: present
    - name: group tomcat
      group:
        name: "{{ tomcat_user }}"
        state: present
    - name: downloading tomcat
      ansible.builtin.get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v{{ version }}/bin/apache-tomcat-{{ version }}.tar.gz 
      dest: /tmp/apache-tomcat-{{ version }}.tar.gz 

