--- 
- name: tomcat9 installation on ubuntu
  become: yes
  hosts: all
  tasks:
    - name: update cache
      apt:
        update_cache: yes
        state: present
    - name: installation of java 11
      apt:
        name: openjdk-11-jdk
        state: present
         